# Generated by Django 5.1.4 on 2024-12-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('AUTHOR', 'Author'), ('EDITOR', 'Editor'), ('ADMIN', 'Admin')], default='USER', max_length=6),
        ),
    ]
