# Generated by Django 5.1.4 on 2024-12-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_contacts_adress_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='adress',
            new_name='address',
        ),
    ]
